In [ ]:
import pandas as pd 
df = pd.read_csv('Combined_dataset.csv')
df.head(100)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
950,13502414,Puma,Men Navy Blue & White Performance Cat Printed ...,4.3,327,1499,NaN,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/135...,...,"{""1_star"":22,""2_stars"":11,""3_stars"":22,""4_star...","[{""percentage"":""78"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""XS"",""value"":""36.61in"",""value_name"":""...","[""rw-13502414_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
951,13621134,Roadster,The Lifestyle Co Men Rust Brown Solid Appliqu...,4.1,312,1399,50.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":27,""2_stars"":18,""3_stars"":31,""4_star...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
952,17686030,Allen Solly Tribe,Men Navy Blue Solid T-shirt,4.3,23,1499,30.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
953,13616400,Arrow New York,Men Beige Printed Round Neck Pure Cotton T-shirt,4.8,13,899,25.0,"""₹674.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,NaN,NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
954,13480864,Aeropostale,Men White Printed Round Neck Pure Cotton T-shirt,4.2,13,1199,NaN,"""₹1,199.00""",INR,http://assets.myntassets.com/assets/images/134...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
955,13622338,Roadster,The Lifestyle Co Men Olive Green Solid Round ...,4.4,54,899,55.0,"""₹404.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":1,""2_stars"":3,""3_stars"":2,""4_stars"":...","[{""percentage"":""86"",""value_name"":""Fit, Just Ri...",MAI███ KN███EAR███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,BEH███ HP███S A█████████LL ███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
956,16295686,Miss & Chief,Boys Pack of 3 Printed T-shirt,3.9,7,1995,71.0,"""₹578.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Home,"[{""size"":""2-3Y"",""value"":""24.4in"",""value_name"":...",NaN,Hom███and███B/1█████████ Am███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
957,16298856,Friskers,Men Pack of 2 Printed Pure Cotton T-shirts,0.0,0,2998,59.0,"""₹1,229.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Fly███,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,"Fla███o 6███jay█████████s, ███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
958,16277914,Parx,Men Black Printed Polo Collar T-shirt,4.9,7,1399,53.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ray███d L███ted███,"[{""size"":""XS"",""value"":""42.5in"",""value_name"":""C...",NaN,"RAY███D L███TED█████████, P███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
959,16292318,Bewakoof,Men White Printed Pockets T-shirt,4.2,17,1399,60.0,"""₹549.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Tight""...",Bew███of ███nds█████████Lim██████,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,"Plo███8, ███ Fl█████████lr,███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
960,19201678,Tokyo Talkies,Women Yellow Printed Extended Sleeves Slim Fit...,4.1,103,699,58.0,"""₹293.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":4,""2_stars"":8,""3_stars"":10,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,3rd███oor███o. █████████Mai███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
961,16923916,Monte Carlo,Women Pack Of 2 Blue & Peach Solid V-Neck Pure...,4.8,13,835,25.0,"""₹835.00""",INR,http://assets.myntassets.com/assets/images/169...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""32.0in"",""value_name"":""To...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
962,10143909,CHKOKKO,Chkokko Men Teal Green Solid Round Neck Traini...,3.7,53,1665,70.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/101...,...,"{""1_star"":10,""2_stars"":1,""3_stars"":11,""4_stars...","[{""percentage"":""72"",""value_name"":""Fit, Just Ri...",DLA███OSS███IVA█████████D,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,FLO███FIR███ B █████████8/1███████████████████...,"[{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
963,20085320,BULLMER,Men Pack of 2 Navy Blue & Turquoise Blue Long ...,4.8,12,3998,80.0,"""₹799.00""",INR,http://assets.myntassets.com/assets/images/200...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bod███ove███par█████████,"[{""size"":""M"",""value"":""39.0in"",""value_name"":""Ch...",NaN,Bod███ove███par█████████ No███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
964,10555034,Braveo,Men Navy Blue and Red Checked Round Neck Pure ...,0.0,0,1099,65.0,"""₹384.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Bra███For███es,"[{""size"":""S"",""value"":""37.5in"",""value_name"":""Ch...",NaN,"SF.███. 8███Vad█████████am,███████████████████...",[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
965,12987894,AMERICAN EAGLE OUTFITTERS,Women White & Yellow Printed Round Neck T-shirt,4.4,5,1799,80.0,"""₹359.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Wes███ry ███din█████████d_M██████,"[{""size"":""XS"",""value"":""29.0in"",""value_name"":""T...",NaN,"Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
966,12953958,Allen Solly,Men Maroon Solid Polo Collar Pure Cotton T-shirt,4.4,409,999,40.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/129...,...,"{""1_star"":17,""2_stars"":6,""3_stars"":26,""4_stars...","[{""percentage"":""96"",""value_name"":""Fit, Just Ri...",Wes███ry ███din█████████d_M██████,"[{""size"":""S"",""value"":""39.0in"",""value_name"":""Ch...","[""rw-12953958_cae700"",""https://videos.myntasse...","Gro███ Fl███, N█████████old███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
967,22629260,max,Striped Polo Collar Short Sleeves T-shirt,4.4,7,799,40.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Lan███rk ███ine█████████t L███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,#41███42/███bla█████████ pa███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
968,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599,58.0,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MAD███R P███T P█████████MIT███,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",NaN,621███ 6n███ kh█████████zia███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
969,19206288,FERANOID,Men Purple Henley Neck Bio Finish T-shirt,4.2,21,1199,50.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":5,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Fer███id,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,B15███ SH███MAR█████████RK ███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
970,19264534,Flying Machine,Men Black & White Printed Pure Cotton Slim Fit...,4.0,102,999,61.0,"""₹389.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":15,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
971,19264536,Flying Machine,Men Rust Orange Melange Pure Cotton Slim Fit T...,3.8,60,1299,61.0,"""₹506.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":5,""2_stars"":7,""3_stars"":7,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
972,16287616,Juniper,Lime Green Mandarin Collar Printed Tunic,4.3,346,1299,51.0,"""₹636.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":16,""2_stars"":14,""3_stars"":35,""4_star...",NaN,AMA███XPO███ IN█████████AL █████████,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,G-9███SIT███RA █████████L A███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tunics
973,16287462,Juniper,Yellow Mandarin Collar Printed Tunic,4.3,335,1299,43.0,"""₹740.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":16,""2_stars"":13,""3_stars"":29,""4_star...",NaN,AMA███XPO███ IN█████████AL,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,G-9███PIP███ICO█████████AL ███████████████████...,"[{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tunics
974,16293014,Nayo,Navy Blue & Maroon Printed Tunic,4.2,514,1199,43.0,"""₹683.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":31,""2_stars"":24,""3_stars"":54,""4_star...",NaN,Bhu███E R███il █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",NaN,"F-███-A,███t, █████████flo███████████████████...","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tunics
975,16293018,Nayo,Black & White Printed Cotton Kurti,4.3,687,1199,43.0,"""₹683.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":32,""2_stars"":28,""3_stars"":51,""4_star...",NaN,Bhu███E R███il █████████,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Bu...",NaN,"F-███-A,███t, █████████flo███████████████████...","[{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tunics
976,13721540,Art Street,Set Of 3 Brown & Green Monuments Theme Framed ...,3.9,8,3500,84.0,"""₹560.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,EDG███QUA███,"[{""size"":""Onesize""}]",NaN,I-6███URA███R I█████████ AR███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",wall-art
977,17716590,Tommy Hilfiger,Women Black Leather Zip Around Wallet,4.5,39,4299,40.0,"""₹4,299.00""",INR,http://assets.myntassets.com/assets/images/177...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",wallets
978,21112784,Calvin Klein,Women Solid Three Fold Wallet,0.0,0,3999,40.0,"""₹2,399.00""",INR,http://assets.myntassets.com/assets/images/211...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Pla███um ███hio███,"[{""size"":""Onesize""}]","[""rw-21112784_cae700"",""https://videos.myntasse...",1ST███OOR███O 5█████████MAH███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",wallets
979,9452773,Louis Philippe,Men Brown Solid Leather Two Fold Wallet,4.3,401,1799,25.0,"""₹1,799.00""",INR,http://assets.myntassets.com/assets/images/945...,...,"{""1_star"":23,""2_stars"":5,""3_stars"":21,""4_stars...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",wallets
980,18864968,Lavie,Glossy Sacy Women Pink Animal Textured Zip Aro...,4.4,21,1999,65.0,"""₹1,999.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""L""}]","[""rw-18864968_cae700""]",NaN,"[{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",wallets
981,9029979,Hidesign,Men Brown Solid Leather Two Fold Wallet,4.4,8,2595,NaN,"""₹2,595.00""",INR,http://assets.myntassets.com/assets/images/902...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",wallets
982,16295388,LOUIS STITCH,Men Brown Leather Two Fold Wallet,4.4,10,4200,75.0,"""₹1,050.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Gun███al ███tch█████████E L█████████,"[{""size"":""Onesize""}]",NaN,"A-1███ Bl███ A,█████████Lok███████████████████...","[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",wallets
983,16295382,LOUIS STITCH,Men Brown & Black Leather Two Fold Wallet,0.0,0,4200,75.0,"""₹1,050.00""",INR,http://assets.myntassets.com/assets/images/162...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Gun███al ███tch█████████E L█████████,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","A-1███ Bl███ A,█████████Lok███████████████████...","[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",wallets
984,17956822,Fossil,Men Black Dial & Leather Straps Dayliner Analo...,3.9,7,9995,50.0,"""₹4,997.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]","[""rw-17956822_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
985,17981742,MVMT,Men Black Raptor Analogue Watch 28000152-D,4.5,11,20832,50.0,"""₹10,416.00""",INR,http://assets.myntassets.com/assets/images/179...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Sup███om ███,"[{""size"":""L""}]",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
986,17697474,Timex,Women White Dial & Gold Toned Analogue Watch T...,4.9,8,1995,20.0,"""₹1,596.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,TIM███T R███IL █████████RIV████████████,"[{""size"":""Onesize""}]",NaN,"Fla███o. ███, 6█████████y C███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1299 (only ...","[{""offer_name"":""10% Instant Discount on Citi C...",watches
987,7349545,Fantasy World,Unisex Grey Digital Watch,3.7,119,499,20.0,"""₹499.00""",INR,http://assets.myntassets.com/assets/images/734...,...,"{""1_star"":20,""2_stars"":8,""3_stars"":13,""4_stars...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-7349545_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
988,8076639,French Connection,Women Charcoal Grey Analogue Watch FC1317RGM,4.4,563,6250,60.0,"""₹6,250.00""",INR,http://assets.myntassets.com/assets/images/807...,...,"{""1_star"":35,""2_stars"":21,""3_stars"":22,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8076639_cae700"",""https://videos.myntasset...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
989,21948792,Adwitiya Collection,Women Embellished Dial & Bracelet Style Straps...,4.1,7,9709,72.0,"""₹9,709.00""",INR,http://assets.myntassets.com/assets/images/219...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
990,9053317,TIMESMITH,Men Black Analogue Watch TSC-008,3.7,304,2499,88.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/905...,...,"{""1_star"":54,""2_stars"":20,""3_stars"":34,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9053317_cae700"",""https://videos.myntasset...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches

In [2]:
print('Shape:',df.shape)
print('Columns:',df.columns.tolist())
print(df.dtypes)

Shape: (1000, 24)
Columns: ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [3]:
print(df.isnull().sum())

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [7]:
for col  in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna('Unknown')

for col in df.select_dtypes(exclude=['object']).columns:
    df[col] = df[col].fillna(df[col].median())

In [8]:
df = df.drop_duplicates()

In [9]:
filtered_df = df[df['rating'] > 4]
filtered_df[['title','rating']].head()

            title  rating
1  Tommy Hilfiger     4.5
2           Lavie     4.4
3          F Gear     4.4
4       MYTRIDENT     4.7
5             H&M     4.5

In [10]:
df['quantity'] = 1
df['final_price_num'] = pd.to_numeric(df['final_price'].astype(str).str.extract(r'(\d+\.?\d*)')[0], errors='coerce').fillna(0)
df['total_amount'] = df['final_price_num'] * df['quantity']
df[['final_price_num','quantity','total_amount']].head()

   final_price_num  quantity  total_amount
0              3.0         1           3.0
1              2.0         1           2.0
2              2.0         1           2.0
3              1.0         1           1.0
4              2.0         1           2.0

In [11]:
df.to_csv('cleaned_dataset.csv', index=False)